Repository ucsb-cs156-s24/proj-happycows-s24-4pm-7, pull requests merged in 2024-05, with the labels that each got.

#20 zc - fix bug for ability to navigate to unjoined commons
  frontend/src/App.js
  frontend/src/main/pages/ProtectedPlayPage.js
  frontend/src/tests/pages/ProtectedPlayPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/CommonsController.java
Labels: Ready for Staff Review, 5

#23 Yixin fold announcementcard
  frontend/package-lock.json
  frontend/package.json
  frontend/src/fixtures/announcementFixtures.js
  frontend/src/main/components/Announcement/AnnouncementCard.js
  frontend/src/stories/components/Announcement/AnnouncementCard.stories.js
  frontend/src/tests/components/Announcement/AnnouncementsCard.test.js
Labels: 5

#25 zc - add Swagger option on navbar
  src/main/resources/application-development.properties
  src/main/resources/application-integration.properties
  src/main/resources/application-production.properties
  src/main/resources/application-wiremock.properties
Labels: Ready for Staff Review

#24 zc - Latest Commit tracker
  Dockerfile
  pom.xml
  src/main/java/edu/ucsb/cs156/happiercows/models/SystemInfo.java
  src/main/java/edu/ucsb/cs156/happiercows/services/SystemInfoServiceImpl.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/SystemInfoControllerTests.java
  src/test/java/edu/ucsb/cs156/happiercows/services/SystemInfoServiceImplTests.java
Labels: 10

#18 na - started refactor of homepage
  frontend/src/main/components/Commons/CommonsList.js
  frontend/src/main/pages/HomePage.css
  frontend/src/main/pages/HomePage.js
  frontend/src/tests/components/Commons/CommonsList.test.js
  frontend/src/tests/pages/HomePage.test.js
Labels: Ready for Staff Review, 5

#29 mz - adding suspended field to user
  src/main/java/edu/ucsb/cs156/happiercows/entities/User.java
Labels: 5

#28 zc - Fixed dateConversion test file
  frontend/package-lock.json
  frontend/package.json
  frontend/src/tests/components/Utils/DateConversion.test.js
Labels: Ready for Staff Review

#35 na - updated pom.xml for partial pitest runs
  README.md
  pom.xml
Labels: Ready for Staff Review

#37 na - further UI refactoring
  frontend/src/main/components/Commons/CommonsCard.js
  frontend/src/main/components/Commons/CommonsList.js
  frontend/src/main/pages/HomePage.css
  frontend/src/main/pages/HomePage.js
  frontend/src/tests/components/Commons/CommonsCard.test.js
  frontend/src/tests/components/Commons/CommonsList.test.js
  frontend/src/tests/pages/HomePage.test.js
Labels: Ready for Staff Review

#15 mz - adding "suspend" button to users table for admins
  frontend/src/App.js
  frontend/src/main/components/Users/UsersTable.js
  frontend/src/main/pages/AdminSuspendUserPage.js
  frontend/src/tests/components/Users/UsersTable.test.js
  frontend/src/tests/pages/AdminSuspendUserPage.test.js
Labels: Ready for Staff Review

#26 Yixin - incorporate announcement card component to play page
  frontend/src/main/components/Announcement/AnnouncementCard.js
  frontend/src/main/components/Commons/CommonsForm.js
  frontend/src/main/components/Commons/CommonsOverview.js
  frontend/src/main/pages/PlayPage.js
  frontend/src/tests/components/Announcement/AnnouncementsCard.test.js
  frontend/src/tests/components/Commons/CommonsOverview.test.js
  frontend/src/tests/pages/PlayPage.test.js
Labels: Ready for Staff Review

#40 jf - fixed an issues where users are unable to login with Oauth
  src/main/java/edu/ucsb/cs156/happiercows/entities/User.java
Labels: 10

#43 rk - homepage UI cleanup and "leave" button
  frontend/src/main/components/Commons/CommonsCard.js
  frontend/src/main/components/Commons/CommonsList.js
  frontend/src/main/pages/HomePage.css
  frontend/src/main/pages/HomePage.js
  frontend/src/tests/pages/HomePage.test.js
Labels: Ready for Staff Review
