Repository ucsb-cs156-s24/proj-happycows-s24-4pm-7, pull requests merged in 2024-06, with the labels that each got.

#36 zc - add announcements button on commons list page
  frontend/src/App.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/main/pages/AdminListAnnouncementsPage.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
  frontend/src/tests/pages/AdminListAnnouncementsPage.test.js
Labels: Ready for Staff Review

#46 zc - announcement page
  frontend/src/main/pages/AdminListAnnouncementsPage.js
  frontend/src/tests/pages/AdminListAnnouncementsPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsControllerTests.java
Labels: 5, Merge Candidate

#47 mz - adding accidentally deleted changes back into main
  frontend/src/App.js
  frontend/src/main/components/Announcement/AnnouncementCard.js
  frontend/src/main/components/Commons/CommonsOverview.js
  frontend/src/main/components/Users/UsersTable.js
  frontend/src/main/pages/AdminSuspendUserPage.js
  frontend/src/main/pages/PlayPage.js
  frontend/src/tests/components/Announcement/AnnouncementsCard.test.js
  frontend/src/tests/components/Commons/CommonsOverview.test.js
  frontend/src/tests/components/Users/UsersTable.test.js
  frontend/src/tests/pages/AdminSuspendUserPage.test.js
  frontend/src/tests/pages/PlayPage.test.js
Labels: Merge Candidate

#49 Announcements Fix #2
  frontend/src/App.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/main/pages/AdminListAnnouncementsPage.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
  frontend/src/tests/pages/AdminListAnnouncementsPage.test.js
  src/main/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/AnnouncementsControllerTests.java
Labels: 0
